FROM node:alpine

WORKDIR /my-app
COPY . .


RUN npm install
RUN npm install express
RUN npm install axios
RUN npm install express-fileupload
RUN npm install ejs
RUN npm install multer
RUN npm install fs
RUN npm install mime-types
# EXPOSE 3004
CMD [ "npm", "start" ]

